[2018-08-03T18:25:03.653] [ERROR] errorLog - registerController{"code":60003,"data":null,"message":"password 数据size错误"}
[2018-08-03T18:25:03.665] [ERROR] errorLog - TypeError: ctx.set is not a function
    at checkRuntime (G:/node/node-service-frame/server/check-runtime/index.js:44:13)
    at Object._callee2$ (G:/node/node-service-frame/server/controller/js/user-ctrl.js:37:19)
    at tryCatch (G:\node\node-service-frame\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (G:\node\node-service-frame\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (G:\node\node-service-frame\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (G:\node\node-service-frame\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at G:\node\node-service-frame\node_modules\babel-runtime\helpers\asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (G:\node\node-service-frame\node_modules\core-js\library\modules\_export.js:36:28)
    at Object.<anonymous> (G:\node\node-service-frame\node_modules\babel-runtime\helpers\asyncToGenerator.js:14:12)
    at Object.registerController (G:/node/node-service-frame/server/controller/js/user-ctrl.js:36:7)
    at _callee2$ (G:/node/node-service-frame/server/routers/index.js:39:23)
    at tryCatch (G:\node\node-service-frame\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (G:\node\node-service-frame\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (G:\node\node-service-frame\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (G:\node\node-service-frame\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
[2018-08-03T18:26:19.690] [ERROR] errorLog - registerController{"code":60003,"data":null,"message":"password 数据size错误"}
[2018-08-03T18:26:19.692] [ERROR] errorLog - TypeError: ctx.set is not a function
    at checkRuntime (G:/node/node-service-frame/server/check-runtime/index.js:44:13)
    at Object._callee2$ (G:/node/node-service-frame/server/controller/js/user-ctrl.js:37:19)
    at tryCatch (G:\node\node-service-frame\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (G:\node\node-service-frame\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (G:\node\node-service-frame\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (G:\node\node-service-frame\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at G:\node\node-service-frame\node_modules\babel-runtime\helpers\asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (G:\node\node-service-frame\node_modules\core-js\library\modules\_export.js:36:28)
    at Object.<anonymous> (G:\node\node-service-frame\node_modules\babel-runtime\helpers\asyncToGenerator.js:14:12)
    at Object.registerController (G:/node/node-service-frame/server/controller/js/user-ctrl.js:36:7)
    at _callee2$ (G:/node/node-service-frame/server/routers/index.js:39:23)
    at tryCatch (G:\node\node-service-frame\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (G:\node\node-service-frame\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (G:\node\node-service-frame\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (G:\node\node-service-frame\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
